language: python
sudo: false   # Since this is an older project, this is not the default.
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7 # https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
      dist: xenial
      sudo: true
install:
  - pip install -U pip setuptools
  - pip install tox-travis
script: tox
notifications:
  email:
    - stix-commits-list@groups.mitre.org
